### ISSUE TITLE
resnet

### ISSUE THREAD

**Issue by TigerAB1** [YMJS-Irfan/DP-FedSAM#6]
您好，我最近在复现代码的时候，500个客户端0.1的参加率的时候，会出现gpu显存的问题，您遇到过吗？

**Comment by YMJS-Irfan** [comment]
> 您好，我最近在复现代码的时候，500个客户端0.1的参加率的时候，会出现gpu显存的问题，您遇到过吗？

您好，我们当时并未碰到过，这样的参数设置在我们当时运行实验时属于服务器可接受的值，或许您可以考虑采用其他超参数设置或者更好的服务器。
祝好！
